function displayBook(response) {
  let output = document.querySelector(".book-recommendation");
  output.innerHTML = "";

  new Typewriter(output, {
    strings: response.data.answer,
    autoStart: true,
    delay: 12,
  });
}

function generateBook(event) {
  event.preventDefault();

  let instructionInput = document.querySelector("#user-instruction");
  let apiKey = "t63c383f46801a32dfab71dd884c0fod";
  let prompt = `generate a book suggestion of ${instructionInput.value}`;
  let context =
    "User instructions are: Give me the latest or most popular book title and summary English language book. Your mission is to answer them book title first then the short summary of the book. Make sure to understand the users genre of book they want. After <strong>Book Title: Title</strong> separate the Summary with a <br/><br/>. add <br/></br> then Sign the ending with <strong></strong> element 'Generated by SheCodes AI'. Generate new title whenever submit form";
  let apiURL = `https://api.shecodes.io/ai/v1/generate?prompt=${prompt}&context=${context}&key=${apiKey}`;

  axios.get(apiURL).then(displayBook);
}

let bookForm = document.querySelector("#book-form");
bookForm.addEventListener("submit", generateBook);
